/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, View, Text} from 'react-native';
import {Demo as Test} from 'react-native-antd-picker';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>aa</Text>
        <Test
          onChange={(v) => {
            console.warn('onChange', v);
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
